<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'atom\\test\\database\\databaseconnectiontest' => '/app/database/DatabaseConnectionTest.php',
                'atom\\test\\database\\generic_tests_databasetestcase' => '/app/database/Generic_Tests_DatabaseTestCase.php',
                'atom\\test\\database\\truncateoperation' => '/app/database/Generic_Tests_DatabaseTestCase.php',
                'atom\\test\\model\\municipiotest' => '/app/model/MunicipioTest.php',
                'atom\\test\\model\\indicadortest' => '/app/model/IndicadorTest.php',
                'atom\\test\\model\\indicetest' => '/app/model/IndiceTest.php',
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    }
);
// @codeCoverageIgnoreEnd
