<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'atom\\database\\databaseconnection' => '/dbconnection/DatabaseConnection.class.php',
                'atom\\model\\indicador' => '/model/Indicador.class.php',
                'atom\\model\\indice' => '/model/Indice.class.php',
                'atom\\model\\municipio' => '/model/Municipio.class.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    }
);
// @codeCoverageIgnoreEnd